twamp:
  controlPort: 862
  senderPortRange: 
    from: 19000
    to: 20000
  receiverPortRange: 
    from: 19000
    to: 20000
  count: 10
  timeout: 1
  ip:
    fallback: true
    version: 6

twamp_100:
  senderPortRange: 
    from: 19000
    to: 19000
  receiverPortrange:
    from: 19000
    to: 19000
  count: 100