twamp:
  controlPort: 862
  senderPortRange: 
    from: 19000
    to: 20000
  receiverPortRange: 
    from: 19000
    to: 20000
  count: 10
  timeout: 1

twamp_100:
  controlPort: 862
  senderPortRange: 
    from: 19000
    to: 19000
  receiverPortrange:
    from: 19000
    to: 19000
  count: 100
  timeout: 1
