name: Go

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: ['amd64', 'arm64']
        goos: ['linux']
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v main.go -o twamp_exporter
        tar -zcvf twamp_exporter LICENSE README.md config.yml twamp_exporter.${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"tag_name\": \"${{ github.ref_name }}, \"target_commitish\": \"master\"}" \
          https://api.github.com/repo/${{ github.repository }}/releases
