name: Go

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: ['amd64', 'arm64']
        goos: ['linux']
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o twamp_exporter -v main.go
 
    - name: gzip
      run: |
        tar -xzcf twamp_exporter.${{ github.ref }}-${{ matrix.goos }}-${{ matrix.goarch }} twamp_exporter config.yaml LICENSE README.md

    - name: release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        preleease: false
