name: Go

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: ['amd64', 'arm64']
        goos: ['linux']
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o twamp_exporter -v main.go
 
    - name: gzip
      run: |
        tar -cf twamp_exporter-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar twamp_exporter config.yaml LICENSE README.md
        gzip twamp_exporter-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.1.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: twamp_exporter-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        asset_name: twamp_exporter-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        tag: ${{ github.ref_name }}
        overwrite: true

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN}}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}